### ISSUE TITLE
CSV should contain German characters (e.g. umlauts)

### ISSUE THREAD

**Issue by aardila** [OpenData-tu/Spring-Batch-Pollution-Data#1]
The original file at http://www.umweltbundesamt.de/en/data/current-concentrations-of-air-pollutants-in-germany#/transgressions?s=LcuxCoAgEAbgd/lnB20JbmtxC3oFscsE0fCuIaJ3b6jxG74b2kOV1FkktyqgG1k8a9xzTaAtFGGDi0MHDdaNBkcr5dRQFYRldhYG0rr6zGUF2U+TxD8/zws=&_k=txddtm ins correctly encoded to support German special characters. The CSV file in the source is not properly encoded to support them.

**Comment by ahmadjawidjami** [comment]
Issue resolved
